# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dootmoon.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1134, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(0, 0, 1131, 631))
        self.photo.setText("")
        self.photo.setPixmap(QtGui.QPixmap("SKULL_TRUMPET_0-1_screenshot.jpg"))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        self.dootButton = QtWidgets.QPushButton(self.centralwidget)
        self.dootButton.setGeometry(QtCore.QRect(160, 690, 191, 51))
        self.dootButton.setObjectName("dootButton")
        self.moonButton = QtWidgets.QPushButton(self.centralwidget)
        self.moonButton.setGeometry(QtCore.QRect(800, 690, 191, 51))
        self.moonButton.setObjectName("moonButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1134, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


        self.dootButton.clicked.connect(self.show_doot)
        self.moonButton.clicked.connect(self.show_moon)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dootButton.setText(_translate("MainWindow", "Doot"))
        self.moonButton.setText(_translate("MainWindow", "Moon"))


    def show_moon(self):
        self.photo.setPixmap(QtGui.QPixmap("images.jpeg"))
        

    def show_doot(self):
        self.photo.setPixmap(QtGui.QPixmap("SKULL_TRUMPET_0-1_screenshot.jpg"))
        



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
